version: '3.7'
services:
  reverse_proxy:
    container_name: remainder_reverse_proxy
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./bundle.crt:/etc/ssl/bundle.crt
      - ./api_matheusinit_me.key:/etc/ssl/api_matheusinit_me.key
  api:
    container_name: remainder_api
    image: matheusinit/nodejs_cicd
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    restart: unless-stopped
  database:
    container_name: remainder_db
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /usr/docker/postgresql/remainder/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
